export const c = {
  bg:           '#F2EDE6',
  bgDark:       '#1F1A12',
  card:         '#FFFFFF',
  input:        '#EAE4DB',
  primary:      '#C09A3A',
  primaryHover: '#A37F28',
  accent:       '#1F1A12',
  textMain:     '#1F1A12',
  textSub:      '#7A7060',
  border:       '#D9D2C7',
  borderDark:   '#3A342B',
  white:        '#FFFFFF',
}

export const styles = {
  page: {
    minHeight: '100vh',
    backgroundColor: c.bg,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '0 16px',
  },
  card: {
    backgroundColor: c.card,
    borderRadius: '16px',
    padding: '32px',
    border: `1px solid ${c.border}`,
    boxShadow: '0 4px 24px rgba(0,0,0,0.08)',
  },
  label: {
    color: c.textSub,
    fontSize: '12px',
    marginBottom: '6px',
    display: 'block',
    textTransform: 'uppercase',
    letterSpacing: '1px',
  },
  input: {
    width: '100%',
    backgroundColor: c.input,
    color: c.textMain,
    border: `1.5px solid ${c.border}`,
    borderRadius: '8px',
    padding: '12px 16px',
    fontSize: '14px',
    outline: 'none',
    boxSizing: 'border-box',
  },
  button: (loading, hovering) => ({
    width: '100%',
    backgroundColor: loading ? '#C4B99A' : hovering ? c.primaryHover : c.primary,
    color: c.bgDark,
    fontWeight: '700',
    padding: '14px',
    borderRadius: '8px',
    fontSize: '14px',
    border: 'none',
    cursor: loading ? 'not-allowed' : 'pointer',
    letterSpacing: '1px',
    textTransform: 'uppercase',
    transition: 'background-color 0.2s',
  }),
  error: {
    backgroundColor: 'rgba(192,154,58,0.1)',
    border: `1px solid ${c.primary}`,
    color: '#8B6914',
    padding: '12px 16px',
    borderRadius: '8px',
    marginBottom: '24px',
    fontSize: '13px',
  },
}